<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>injectionSelector</key>
	<string>L:text.html.markdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code-inline-r</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>code-inline-r</key>
				<dict>
					<key>begin</key>
					<string>(`[r|R][ ]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.rmarkdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(`)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.rmarkdown</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.r</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.r</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>rmd.inline</string>
</dict>
</plist>
